variables:
  vmImage: 'ubuntu-18.04'
  majorVersion: 0
  minorVersion: 0
  containerRegistry: 'Container Registry - Release'
  imageName: sorena/light-ssr
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    buildPrefix: ''
    buildSuffix: ''
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    buildPrefix: release-
    buildSuffix: -${{ variables['Build.SourceBranchName'] }}

name: $(buildPrefix)$(majorVersion).$(minorVersion)$(Rev:.r)$(buildSuffix)

trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - README.md

stages:

- stage: build
  displayName: Build & Push
  jobs:

  - job: Build Docker
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Docker@2
        displayName: Build & push image
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(imageName)
          tags: $(Build.BuildNumber)
          command: buildAndPush
          Dockerfile: Dockerfile
